import { binominalProbability } from './utils';

export enum ATTRIBUTE {
  HP,
  ATK,
  DEF,
  EM,
  HP_PERCENT,
  ATK_PERCENT,
  DEF_PERCENT,
  ER_PERCENT,
  PYRO_DMG_BONUS,
  ELECTRO_DMG_BONUS,
  CRYO_DMG_BONUS,
  HYDRO_DMG_BONUS,
  DENDRO_DMG_BONUS,
  ANEMO_DMG_BONUS,
  GEO_DMG_BONUS,
  PHYSICAL_DMG_BONUS,
  CRIT_RATE,
  CRIT_DMG,
  HEALING_BONUS,
}

export const mainAffixProbabilities = {
  flower: {
    [ATTRIBUTE.HP]: 1,
  },
  plume: {
    [ATTRIBUTE.ATK]: 1,
  },
  sands: {
    [ATTRIBUTE.HP_PERCENT]: 0.2668,
    [ATTRIBUTE.ATK_PERCENT]: 0.2666,
    [ATTRIBUTE.DEF_PERCENT]: 0.2666,
    [ATTRIBUTE.ER_PERCENT]: 0.1,
    [ATTRIBUTE.EM]: 0.1,
  },
  goblet: {
    [ATTRIBUTE.HP_PERCENT]: 0.1925,
    [ATTRIBUTE.ATK_PERCENT]: 0.1925,
    [ATTRIBUTE.DEF_PERCENT]: 0.19,
    [ATTRIBUTE.PYRO_DMG_BONUS]: 0.05,
    [ATTRIBUTE.ELECTRO_DMG_BONUS]: 0.05,
    [ATTRIBUTE.CRYO_DMG_BONUS]: 0.05,
    [ATTRIBUTE.HYDRO_DMG_BONUS]: 0.05,
    [ATTRIBUTE.DENDRO_DMG_BONUS]: 0.05,
    [ATTRIBUTE.ANEMO_DMG_BONUS]: 0.05,
    [ATTRIBUTE.GEO_DMG_BONUS]: 0.05,
    [ATTRIBUTE.PHYSICAL_DMG_BONUS]: 0.05,
    [ATTRIBUTE.EM]: 0.05,
  },
  circlet: {
    [ATTRIBUTE.HP_PERCENT]: 0.22,
    [ATTRIBUTE.ATK_PERCENT]: 0.22,
    [ATTRIBUTE.DEF_PERCENT]: 0.22,
    [ATTRIBUTE.CRIT_RATE]: 0.1,
    [ATTRIBUTE.CRIT_DMG]: 0.1,
    [ATTRIBUTE.HEALING_BONUS]: 0.1,
    [ATTRIBUTE.EM]: 0.04,
  },
} as const;

const ELEMENTAL_DMG_BONUS = '46.6%';

export const mainAffixMaxValue = {
  [ATTRIBUTE.HP]: '4780',
  [ATTRIBUTE.HP_PERCENT]: '46.6%',
  [ATTRIBUTE.ATK]: '311',
  [ATTRIBUTE.ATK_PERCENT]: '46.6%',
  [ATTRIBUTE.DEF_PERCENT]: '58.3%',
  [ATTRIBUTE.CRIT_RATE]: '31.1%',
  [ATTRIBUTE.CRIT_DMG]: '62.2%',
  [ATTRIBUTE.ER_PERCENT]: '51.8%',
  [ATTRIBUTE.HEALING_BONUS]: '35.9%',
  [ATTRIBUTE.EM]: 187,
  [ATTRIBUTE.PYRO_DMG_BONUS]: ELEMENTAL_DMG_BONUS,
  [ATTRIBUTE.ELECTRO_DMG_BONUS]: ELEMENTAL_DMG_BONUS,
  [ATTRIBUTE.CRYO_DMG_BONUS]: ELEMENTAL_DMG_BONUS,
  [ATTRIBUTE.HYDRO_DMG_BONUS]: ELEMENTAL_DMG_BONUS,
  [ATTRIBUTE.DENDRO_DMG_BONUS]: ELEMENTAL_DMG_BONUS,
  [ATTRIBUTE.ANEMO_DMG_BONUS]: ELEMENTAL_DMG_BONUS,
  [ATTRIBUTE.GEO_DMG_BONUS]: ELEMENTAL_DMG_BONUS,
  [ATTRIBUTE.PHYSICAL_DMG_BONUS]: '58.3%',
} as const;

export const minorAffixAttributeWeights = {
  [ATTRIBUTE.HP]: 6,
  [ATTRIBUTE.ATK]: 6,
  [ATTRIBUTE.DEF]: 6,
  [ATTRIBUTE.HP_PERCENT]: 4,
  [ATTRIBUTE.ATK_PERCENT]: 4,
  [ATTRIBUTE.DEF_PERCENT]: 4,
  [ATTRIBUTE.ER_PERCENT]: 4,
  [ATTRIBUTE.EM]: 4,
  [ATTRIBUTE.CRIT_RATE]: 3,
  [ATTRIBUTE.CRIT_DMG]: 3,
} as const;

// 100%, 90%, 80%, 70%
export const MINOR_AFFIX_VALUE_PROBABILITY = 0.25;

// slot 1, 2, 3, 4
export const MINOR_AFFIX_SLOT_UPGRADE_PROBABILITY = 0.25;

export const MAX_UPGRADES = 5;

// by index
export const minorAffixSlotUpgradeTimesProbabilities = Array(MAX_UPGRADES).map(
  (_, i) => binominalProbability(MAX_ROLLS, i, MINOR_AFFIX_SLOT_UPGRADE_PROBABILITY),
);
